# Generated by Django 2.1 on 2019-05-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('EPT', 'Пусто'), ('OCP', 'Занято'), ('CLN', 'Уборка'), ('RPR', 'Ремонт')], default='EPT', max_length=2)),
                ('configuration', models.CharField(choices=[('DBL', 'Double'), ('TWN', 'Twin'), ('RND', 'Круглая'), ('DBL+SF', 'Double+Диван'), ('TWN+SF', 'Twin+Диван')], default='DBL', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('daily_price', models.FloatField()),
                ('hourly_price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.RoomTypes'),
        ),
    ]
