# Generated by Django 2.1 on 2019-05-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190522_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='daily_price',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='hourly_price',
        ),
        migrations.AddField(
            model_name='room',
            name='daily_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='hourly_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
