# Generated by Django 2.1 on 2019-05-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190522_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('EPT', 'Пусто'), ('OCP', 'Занято'), ('CLN', 'Уборка'), ('RPR', 'Ремонт')], default='EPT', max_length=3),
        ),
    ]
