# Generated by Django 2.1 on 2019-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190522_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomnote',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
