# Generated by Django 2.2.1 on 2019-05-25 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190522_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=50)),
                ('document_issued_by', models.CharField(max_length=100)),
                ('document_issued_on', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.DocumentType')),
            ],
        ),
        migrations.CreateModel(
            name='GuestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/guests/%Y/%m/%d/')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Guest')),
            ],
        ),
    ]
