# Generated by Django 2.2.1 on 2019-05-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20190525_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='relations',
            field=models.ManyToManyField(related_name='_guest_relations_+', to='backend.Guest'),
        ),
    ]
