# Generated by Django 2.2.1 on 2019-05-26 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_guest_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='abc_status',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='guest',
            name='first_visit',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='last_visit',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
