# Generated by Django 2.2.1 on 2019-05-28 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20190527_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('accommodation_type', models.CharField(choices=[('HOURLY', 'H'), ('DAILY', 'D')], default='DAILY', max_length=1)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('guests', models.ManyToManyField(null=True, to='backend.Guest')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CASH', 'Наличные'), ('BANK', 'Банковский перевод'), ('POS', 'Оплата картой')], default='CASH', max_length=4)),
                ('amount', models.FloatField()),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('accomodation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Accommodation')),
            ],
        ),
        migrations.DeleteModel(
            name='Occupancy',
        ),
    ]
