# Generated by Django 2.2.1 on 2019-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20190528_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='guests',
            field=models.ManyToManyField(to='backend.Guest'),
        ),
    ]
