# Generated by Django 2.2.1 on 2019-06-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20190528_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='abc_status',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='relations',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_guests', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('NOT_CONFIRMED', 'X'), ('CONFIRMED', 'A'), ('CANCELED', 'C'), ('NO_SHOW', 'N'), ('CHECKED_IN', 'I')], default='NOT_CONFIRMED', max_length=2)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('guest_name', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.RoomType')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.BookingSource')),
            ],
        ),
    ]
