# Generated by Django 2.2.1 on 2019-06-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20190605_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='personal_card_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='personal_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
