# Generated by Django 2.2.1 on 2019-06-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20190608_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='personal_card_number',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='personal_discount',
        ),
        migrations.AddField(
            model_name='guest',
            name='personal_card_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='personal_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
