# Generated by Django 2.2.1 on 2019-06-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20190608_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Room'),
        ),
    ]
