# Generated by Django 2.2.1 on 2019-06-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20190609_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='sex',
            field=models.CharField(choices=[('M', 'муж.'), ('F', 'жен.'), ('O', 'прочий')], default='M', max_length=1),
        ),
    ]
