# Generated by Django 2.2.1 on 2019-06-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_guest_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='citizenship',
            field=models.CharField(default='Российская Федерация', max_length=50),
            preserve_default=False,
        ),
    ]
