# Generated by Django 2.2.1 on 2019-06-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_guest_citizenship'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='home_address',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
