# Generated by Django 2.2.1 on 2019-06-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20190612_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.CharField(choices=[('H', 'Почасовая'), ('D', 'Дневная')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='guest',
            name='home_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='GuestImage',
        ),
    ]
